### ISSUE TITLE
email to admin if unsuccessful search

### ISSUE THREAD

**Issue by abid-zahid** [bennettmcelwee/Search-Meter#11]
actually it is not a issue but a better enhancement for example if user search "flower" and flower not found in records then plugin will send an email to admin about keyword which not found

**Comment by liviutudor** [comment]
My 2 cents: if this is implemented it should be an on/off switch -- in the case of my blog I seem to get spikes 4-5 times a month of "search spam" where random terms are used in the search box. (Still haven't figured out why bots are doing this -- some sort of DDoS I suppose). This would spam the heck out of my inbox.

**Comment by bennettmcelwee** [comment]
I think there's too much potential for email spamming, so I won't add this feature for the time being.
