### ISSUE TITLE
Declare compatibility with latest WordPress version

### ISSUE THREAD

**Issue by patrickrobrecht** [bennettmcelwee/Search-Meter#17]
https://wordpress.org/plugins/search-meter/ says: This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.

Search Meter seems to be compatible with WordPress 4.9, so why don't update `readme.txt`?

**Comment by bennettmcelwee** [comment]
Done. Thanks for the reminder.
