### ISSUE TITLE
Code error in the routine for storing recent searches

### ISSUE THREAD

**Issue by vrocks** [bennettmcelwee/Search-Meter#2]
You have a code error on line #321 in file search-meter.php.

The variable that should be referenced on this line is $hit_count, not $search_terms.

With the error the 100 and 500 last searches do not show the number of returned search results for each search. In addition, the recent searches widget breaks as well.

**Comment by bennettmcelwee** [comment]
Thanks for spotting that embarrassing glitch. Fixing it now.

**Comment by bennettmcelwee** [comment]
This fix was released in version 2.11.
