### ISSUE TITLE
No license present

### ISSUE THREAD

**Issue by liviutudor** [bennettmcelwee/Search-Meter#6]
I noticed your repo doesn't have any license attached to it -- which as I learned recently means it's actually **NOT** open source.
This is just a suggestion that you ought to add one of the standard licenses to your project -- which might encourage other developers to use/extend/etc your code. My suggestion is the MIT license.

**Comment by bennettmcelwee** [comment]
Hi there,

Thanks for your email! (And tweet.) The license statements are in the 
php files: the plugin in licensed under the GPL. You're right, I should 
add a separate license file to make this clearer.


Cheerio,

Bennett.

--
Bennett McElwee
bennett@thunderguy.com

**Comment by liviutudor** [comment]
Cool. Do you want me to send you a pull request with just the GPL license?
Also want to start a separate conversation about this project -- are you open to an email discussion about this ? (I don't think the Issue facility on GH is a good place for this discussion and Twitter is only 140 chars :)

**Comment by bennettmcelwee** [comment]
Updated licence info and included a LICENCE file in version 2.13.
